# Generated by Django 4.2.2 on 2023-07-19 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_activity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='activty_level',
            new_name='level',
        ),
    ]
