# Generated by Django 4.2.2 on 2023-07-19 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_activty_level_activity_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='DogOwnerWants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=150)),
                ('activitys', models.ManyToManyField(to='main_app.activity')),
            ],
        ),
    ]
